apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: billing-module-30245
  namespace: MendPerformance
  annotations:
    github.com/project-slug: MendPerformance/billing-module-30245
spec:
  type: service
  lifecycle: unknown
  owner: mend.io
